
services:
  app:
    build: .
    ports: 
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=your_user  # Match with POSTGRES_USER
      - DATABASE_PASSWORD=your_password  # Match with POSTGRES_PASSWORD
      - DATABASE_NAME=your_database  # Match with POSTGRES_DB
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    ports:
      - "5432:5432"
